version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "groffery-user"
s3_bucket = "aws-sam-cli-managed-bucket"
s3_prefix = "groffery-user"
region = "us-east-1"
profile = "hack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
